"""
OTDR Dataset Visualization Toolkit
====================================
Plotting utilities for inspecting synthetic OTDR traces generated by
otdr_dataset_generator.py -- both live-generated examples and traces already
saved to a CSV/raw-trace dataset on disk.

Usage examples
--------------
# Grid of one example per fault class (freshly generated, not from disk)
python otdr_visualize.py --mode class_grid --snr 12

# Same fault type at several SNR levels, side by side
python otdr_visualize.py --mode snr_sweep --event_class 6 --snrs -5 0 5 10 15 20

# A specific saved sample from a generated dataset
python otdr_visualize.py --mode single --csv my_otdr_dataset/OTDR_dataset.csv \
    --raw_dir my_otdr_dataset/otdr_raw --sample_id sample_000012

# Overview plots (class balance, SNR distribution, location distribution)
python otdr_visualize.py --mode overview --csv my_otdr_dataset/OTDR_dataset.csv

# A compound/overlapping-event trace (freshly generated)
python otdr_visualize.py --mode compound --n_events 3
"""

import argparse
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # safe for headless/script use; drop this line in Jupyter
import matplotlib.pyplot as plt

from otdr_dataset_generator import (
    generate_single_sample, generate_compound_sample, CLASSES,
)


def plot_trace(ax, distance_km, trace_db, events=None, title=""):
    ax.plot(distance_km, trace_db, lw=0.6, color="#1f6feb")
    if events:
        for ev in events:
            loc = ev.get("location_km")
            if loc is None or (isinstance(loc, float) and np.isnan(loc)):
                continue
            ax.axvline(loc, color="crimson", ls="--", lw=0.9, alpha=0.75)
    ax.set_xlabel("Distance (km)")
    ax.set_ylabel("Power (dB)")
    ax.set_title(title, fontsize=10)
    ax.grid(alpha=0.25, lw=0.4)


def event_label(name, loc, refl=None, loss=None):
    label = f"{name} @ {loc:.2f} km"
    if refl is not None and not (isinstance(refl, float) and np.isnan(refl)):
        label += f", refl={refl:.1f} dB"
    if loss is not None and not (isinstance(loss, float) and np.isnan(loss)):
        label += f", loss={loss:.1f} dB"
    return label


def plot_class_grid(snr_db=12.0, seed=1, save_path="otdr_class_grid.png"):
    rng = np.random.default_rng(seed)
    fig, axes = plt.subplots(4, 2, figsize=(11, 13))
    for ax, cls in zip(axes.flat, range(8)):
        s = generate_single_sample(rng, snr_range=(snr_db, snr_db), event_class=cls)
        events = [{"location_km": s["location_km"]}] if not np.isnan(s["location_km"]) else []
        title = event_label(CLASSES[cls], s["location_km"], s["reflectance_db"], s["loss_db"]) \
            if events else CLASSES[cls]
        plot_trace(ax, s["distance_km"], s["trace_raw"], events, title)
    fig.suptitle(f"One example per fault class (SNR = {snr_db} dB)", fontsize=13)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.savefig(save_path, dpi=140)
    print(f"Saved {save_path}")


def plot_snr_sweep(event_class=6, snr_list=(-5, 0, 5, 10, 15, 20), seed=2,
                    save_path="otdr_snr_sweep.png"):
    rng = np.random.default_rng(seed)
    fig, axes = plt.subplots(len(snr_list), 1, figsize=(9, 2.2 * len(snr_list)))
    if len(snr_list) == 1:
        axes = [axes]
    for ax, snr in zip(axes, snr_list):
        s = generate_single_sample(rng, snr_range=(snr, snr), event_class=event_class)
        events = [{"location_km": s["location_km"]}] if not np.isnan(s["location_km"]) else []
        plot_trace(ax, s["distance_km"], s["trace_raw"], events,
                   title=f"{CLASSES[event_class]} — SNR = {snr} dB")
    fig.suptitle(f"Same fault type ({CLASSES[event_class]}) across SNR conditions", fontsize=13)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.savefig(save_path, dpi=140)
    print(f"Saved {save_path}")


def plot_compound(n_events=3, snr_range=(8, 15), seed=3, save_path="otdr_compound.png"):
    rng = np.random.default_rng(seed)
    s = generate_compound_sample(rng, snr_range=snr_range, n_events=n_events)
    fig, ax = plt.subplots(figsize=(10, 4.5))
    plot_trace(ax, s["distance_km"], s["trace_raw"], s["events"],
               title=f"Compound trace: {n_events} events (SNR={s['snr_db']:.1f} dB)")
    legend_lines = [event_label(ev["class_name"], ev["location_km"],
                                 ev.get("reflectance_db"), ev.get("loss_db"))
                    for ev in s["events"]]
    ax.text(1.02, 0.5, "\n".join(legend_lines), transform=ax.transAxes, fontsize=8, va="center")
    plt.tight_layout()
    plt.savefig(save_path, dpi=140, bbox_inches="tight")
    print(f"Saved {save_path}")


def plot_single_from_disk(csv_path, sample_id, raw_dir=None, save_path=None):
    df = pd.read_csv(csv_path)
    row = df[df["sample_id"] == sample_id]
    if row.empty:
        raise ValueError(f"sample_id '{sample_id}' not found in {csv_path}")
    row = row.iloc[0]

    if raw_dir:
        trace = np.load(f"{raw_dir}/{sample_id}.npy")
        distance = np.linspace(0, row["fiber_length_km"], len(trace))
    else:
        p_cols = [c for c in df.columns if c.startswith("P")]
        trace = row[p_cols].values.astype(float)
        distance = np.linspace(0, row["fiber_length_km"], len(trace))

    events = [{"location_km": row["location_km"]}] if not pd.isna(row.get("location_km", np.nan)) else []
    fig, ax = plt.subplots(figsize=(9, 4.5))
    title = event_label(row["class_name"], row.get("location_km", np.nan),
                         row.get("reflectance_db"), row.get("loss_db")) if events \
        else f"{row['class_name']} (no event)"
    title += f"  |  SNR={row['snr_db']:.1f} dB  |  id={sample_id}"
    plot_trace(ax, distance, trace, events, title)
    plt.tight_layout()
    out = save_path or f"otdr_{sample_id}.png"
    plt.savefig(out, dpi=140)
    print(f"Saved {out}")


def plot_dataset_overview(csv_path, save_path="otdr_dataset_overview.png"):
    df = pd.read_csv(csv_path)
    fig, axes = plt.subplots(2, 2, figsize=(12, 9))

    counts = df["class_name"].value_counts().sort_index()
    axes[0, 0].bar(counts.index, counts.values, color="#1f6feb")
    axes[0, 0].set_title("Class balance")
    axes[0, 0].tick_params(axis="x", rotation=45, labelsize=8)

    axes[0, 1].hist(df["snr_db"], bins=30, color="#2ea043")
    axes[0, 1].set_title("SNR distribution")
    axes[0, 1].set_xlabel("SNR (dB)")

    loc = df["location_norm"].dropna()
    axes[1, 0].hist(loc, bins=30, color="#d29922")
    axes[1, 0].set_title("Event location distribution (normalized position)")
    axes[1, 0].set_xlabel("Location / fiber length")

    axes[1, 1].hist(df["fiber_length_km"], bins=30, color="#8250df")
    axes[1, 1].set_title("Fiber length distribution")
    axes[1, 1].set_xlabel("Fiber length (km)")

    plt.tight_layout()
    plt.savefig(save_path, dpi=140)
    print(f"Saved {save_path}")


def plot_reflectance_by_class(seed=4, n_draws=400, save_path="otdr_reflectance_by_class.png"):
    """Sanity-check plot: draw many reflectance samples per reflective class
    and show they land in the corrected, physically realistic (negative dB)
    ranges, with the derived visible spike height alongside."""
    from otdr_dataset_generator import (
        draw_reflectance, reflectance_to_spike_db, REFLECTIVE_CLASSES,
    )
    rng = np.random.default_rng(seed)
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    for cls in sorted(REFLECTIVE_CLASSES):
        vals = [draw_reflectance(cls, rng) for _ in range(n_draws)]
        spikes = [reflectance_to_spike_db(v) for v in vals]
        axes[0].hist(vals, bins=30, alpha=0.6, label=CLASSES[cls])
        axes[1].hist(spikes, bins=30, alpha=0.6, label=CLASSES[cls])
    axes[0].axvline(0, color="k", lw=1)
    axes[0].set_title("Physical reflectance label (dB) -- must be <= 0")
    axes[0].set_xlabel("reflectance_db")
    axes[0].legend(fontsize=8)
    axes[1].set_title("Derived visible spike height (dB above backscatter)")
    axes[1].set_xlabel("spike_db (rendering only, not a label)")
    axes[1].legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(save_path, dpi=140)
    print(f"Saved {save_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["class_grid", "snr_sweep", "compound",
                                        "single", "overview", "reflectance_check"],
                     required=True)
    ap.add_argument("--snr", type=float, default=12.0)
    ap.add_argument("--snrs", type=float, nargs="+", default=[-5, 0, 5, 10, 15, 20])
    ap.add_argument("--event_class", type=int, default=6)
    ap.add_argument("--n_events", type=int, default=3)
    ap.add_argument("--csv", type=str, default=None)
    ap.add_argument("--raw_dir", type=str, default=None)
    ap.add_argument("--sample_id", type=str, default=None)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", type=str, default=None)
    args = ap.parse_args()

    if args.mode == "class_grid":
        plot_class_grid(snr_db=args.snr, seed=args.seed, save_path=args.out or "otdr_class_grid.png")
    elif args.mode == "snr_sweep":
        plot_snr_sweep(event_class=args.event_class, snr_list=args.snrs, seed=args.seed,
                        save_path=args.out or "otdr_snr_sweep.png")
    elif args.mode == "compound":
        plot_compound(n_events=args.n_events, seed=args.seed, save_path=args.out or "otdr_compound.png")
    elif args.mode == "single":
        assert args.csv and args.sample_id, "--csv and --sample_id are required for --mode single"
        plot_single_from_disk(args.csv, args.sample_id, args.raw_dir, args.out)
    elif args.mode == "overview":
        assert args.csv, "--csv is required for --mode overview"
        plot_dataset_overview(args.csv, save_path=args.out or "otdr_dataset_overview.png")
    elif args.mode == "reflectance_check":
        plot_reflectance_by_class(seed=args.seed, save_path=args.out or "otdr_reflectance_by_class.png")


if __name__ == "__main__":
    main()
